config/routes.rb
Rails.application.routes.draw do
  #get "todos", to: "todos#index"
  #post "todos/create", to: "todos#create"
  #get "todos/:id", to: "todos#show"
  get "/" => "home#index"
  resources :todos
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  #get "users/login", to: "users#login"
  #post "users/create", to:"users#create"
  resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: true


  belongs_to :user
    def pls_string
    is_completed = completed ? "[x]": "[]"
    "#{id}.#{due_date.to_s(:long)}.#{todo_text}.#{is_completed}"
    end
    
    def self.overdue
        all.where("due_date < ? and (not completed)", Date.today)
    end
    def self.of_user(user)
      all.where(user_id: user.id)
    end
    
      def self.due_today
        all.where("due_date = ?", Date.today)
      end
    
      def self.due_later
        all.where("due_date > ?", Date.today)
      end
      def due_today?
        due_date == Date.today
      end
    
      def self.completed
        all.where(completed: true)
      end


end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :todos
    validates :name, presence: true
    validates :email, presence: true
    has_secure_password
    def to_formatted_string
        "#{id}.  #{name} #{last_name} - #{email}-#{password}"
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :ensure_user_logged_in
  
    def ensure_user_logged_in
      unless current_user
        redirect_to "/"
      end
    end
  
    def current_user
      return @current_user if @current_user
      current_user_id = session[:current_user_id]
      if current_user_id
        @current_user = User.find(current_user_id)
      else
        nil
      end
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
     skip_before_action :ensure_user_logged_in
   
     def index
       if current_user
         redirect_to todos_path
       else
         render "index"
       end
     end
   end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in
    def new
    end

    def create
        user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Your login attempt was invalid. Please retry."
      redirect_to new_sessions_path
    end
    end

    def destroy
      session[:current_user_id]= nil
      @current_user = nil
      redirect_to "/"
    end


end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  #skip_before_action :ensure_user_logged_in
    def index
        #render plain: Todo.order(:id).map{|todo| todo.pls_string}.join("\n")
        @todos = current_user.todos
        render "index"
      end
      def show
        id=params[:id]
        todo=Todo.of_user(current_user).find(id)
        render "todo"
        #render plain: todo.pls_string
        
      end
      def create
        todo_text=params[:todo_text]
        due_date=params[:due_date]
        new_todo=Todo.new(todo_text: todo_text,due_date: due_date,completed: false,
          user_id: current_user.id)
          if new_todo.save
            redirect_to todos_path
          else
            flash[:error] = new_todo.errors.full_messages.join(", ")
            redirect_to todos_path
          end
      end
      def update
        id=params[:id]
        completed= params[:completed]
        todo=Todo.of_user(current_user).find(id)
        todo.completed= completed
        todo.save!
        redirect_to todos_path
      end
      def destroy
        id=params[:id]
        todo=Todo.of_user(current_user).find(id)
        todo.destroy
        redirect_to todos_path
      end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verify_authenticity_token
    skip_before_action :ensure_user_logged_in

    def index
    render plain: User.all.map {|user| user.to_formatted_string}.join("\n")
    end

    def new
      render "users/new"
    end

    
    def create
    name = params[:name]
    last_name = params[:last_name]
    email = params[:email]
    password = params[:password]
    new_user = User.new(
      name: name,
      email: email,
      password: password,last_name: last_name
    )
    if new_user.save
      redirect_to "/"
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
     end

     def login
        email = params[:email]
        password = params[:password]
        if User.where("email = ? and password = ?", email,password).empty?
          render plain: "FALSE! Login FAILED."
        else
          render plain: "TRUE! Login SUCCESSFUL."
        end
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<p class="Home-title">Welcome to homepage</p>

<h3 class="Home-authenticate">
    If you are a new user , <%= link_to "signup here ", new_user_path%>
</h3>

<h3 class="Home-authenticate">
    If you are an existing user , <%= link_to "signin here ", new_sessions_path%>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if @current_user %>
     <p class="UserHeader"> <%= @current_user.name%>
     <%= link_to "signout", destroy_session_path, method: "delete"%>
     </p>
    <%end%>
    <%if flash[:error]%>
        <p class="Flash-error">
        <%= flash[:error] %>
        </p>

    <% end%>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <p class="TodoSectionTitle-text"> <%= section_title %> </p>
    <p class="TodoSectionTitle-remainingCount">
      <%= todos.completed.count %> / <%= todos.count %>
    </p>
  </div>
  <ul>

    <% todos.all.each do |todo| %>
      <li class="TodoItem">
        <label class="TodoItem-Container">
          <%= form_with(url: "/todos/#{todo.id}" , method: "PUT") do %>
            <input class="TodoIt-Checkbox"
              name="completed"
              type="checkbox" <%= todo.completed ? "checked" : "" %>
              onclick="this.form.submit()"
            >
          <% end %>

          <p class = "<%= todo.completed ? "TodoItem-completedText" : "" %> ">
            <%= todo.todo_text %>
          </p>

          <% if show_due_date %>
            <p class="TodoItem-dueDate"> <%= todo.due_date.to_s(:short) %> </p>
          <% end %>
          <a href="javascript:void(0)" class="TodoItem-delete">
            <%= form_with(url: "/todos/#{todo.id}" , method: "DELETE" ) do %>
              <input type="image" src="delete-24px.svg">
            <% end %>
          </a>
          </label>
      </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
 <main class="TodoPageMain">
    <h1 class="TodoPage-title">My Todo-list</h1>
     <%= form_with(url: "/todos", method: "POST", class: "AddToDo") do %>
        <input class="AddTodo-text" type="text" placeholder="What's next?" name="todo_text">
        <input class="AddTodo-date" type="date" name="due_date">
        <input class="AddTodo-button" type="submit" value="Add">
     <%end%>
    
         <%= render partial: "todo-section", locals:{section_title: "Overdue",todos: @todos.overdue,show_due_date: true} %>
         <%= render partial: "todo-section", locals:{section_title: "Due Today",todos: @todos.due_today,show_due_date: false} %>
         <%= render partial: "todo-section", locals:{section_title: "Due Later",todos: @todos.due_later,show_due_date: true} %>
    
      
  </main>

app/views/todos/todo.html.erb
<p>A single Todo<p>

app/views/users/new.html.erb
<p class="NewUsers-title">Welcome new User!</p>

<section class="Usersnew">
  <%= form_with url: users_path do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">First Name: </p>
      <%= form.text_field :name, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Last Name: </p>
      <%= form.text_field :last_name, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Email: </p>
      <%= form.email_field :email, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Password: </p>
      <%= form.password_field :password, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <%= form.submit "Sign-Up!", class: "Form-submit" %>
    </div>
  <% end %>
</section>